#include "configs.h"

const u32 ability_texture_map[ABILITYKIND_COUNT] = {
    [ABILITYKIND_IDLE]     = 0,
    [ABILITYKIND_CLAW]     = SOL_TEXTURE_BLADE_CARD,
    [ABILITYKIND_FIREBALL] = SOL_TEXTURE_FIREBALL_CARD,
    [ABILITYKIND_SHIELD]   = SOL_TEXTURE_CRYSTAL_CARD,
};

const char *ability_name[ABILITYKIND_COUNT] = {
    [ABILITYKIND_IDLE]     = "Idle",     //
    [ABILITYKIND_CLAW]     = "Claw",     //
    [ABILITYKIND_FIREBALL] = "Fireball", //
    [ABILITYKIND_SHIELD] = "Shield", //
};

const char *ability_state_name[ABILITY_STATE_COUNT] = {
    [ABILITY_STATE_IDLE]            = "ABILITY_STATE_IDLE",
    [ABILITY_STATE_CLAW]            = "ABILITY_STATE_CLAW",
    [ABILITY_STATE_CLAW_CHARGE]     = "ABILITY_STATE_CLAW_CHARGE",
    [ABILITY_STATE_CLAW_DASH]       = "ABILITY_STATE_CLAW_DASH",
    [ABILITY_STATE_FIREBALL]        = "ABILITY_STATE_FIREBALL",
    [ABILITY_STATE_FIREBALL_CHARGE] = "ABILITY_STATE_FIREBALL_CHARGE",
    [ABILITY_STATE_FIREBALL_DASH]   = "ABILITY_STATE_FIREBALL_DASH",
};
